### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by molecular** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#2]
ran into the following exception while running inter-wallet-transfer:

```
wallet loaded
wallet loaded
wallet loaded
transferring utxo
transferring utxo
transferring utxo
transferring utxo
Traceback (most recent call last):
  File "/home/nick/bitcoin/electron-cash/lib/util.py", line 730, in run_with_except_hook
    run_original(*args2, **kwargs2)
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/nick/.electron-cash/external_plugins/inter-wallet-transfer-v1.0.zip/inter-wallet-transfer/ui.py", line 176, in send_all
  File "/home/nick/.electron-cash/external_plugins/inter-wallet-transfer-v1.0.zip/inter-wallet-transfer/ui.py", line 187, in send_tx
  File "/home/nick/bitcoin/electron-cash/lib/transaction.py", line 552, in from_io
    for output in outputs)
AssertionError
```

note: I had restarted the process a couple of times in the beginning because I wanted to make unrelated transactions. Those where not confirmed when I started the transfer process. Maybe this is unrelated, but I thought I'd mention it.

note2: none of the 28 transactions generated (over the span of about 30 minutes) have confirmed at this point. Can't really tell why. This may also be unrelated. EDIT: they all confirmed now in the same block.

**Comment by KarolTrzeszczkowski** [comment]
> note2: none of the 28 transactions generated (over the span of about 30 minutes) have confirmed at this point. Can't really tell why. This may also be unrelated. EDIT: they all confirmed now in the same block.

The block time in the Bitcoin Cash is 10 minutes, but it's a statistics, sometimes the block time is longer, even up to 1 hour and sometimes it's shorter. I'd recommend having less than 6 transactions per hour.

Thank you for posting this issue, I'll add this recommendation to the user interface. 
The error you have happens when the coin the wallet tries to send is not there. You should disable shuffling, if it was going while the plugin was working, I see the second issue, it's probably related. I'll make clear in the popup message and catch this error, so it won't bother people in the future. Thank you for reporting it.

**Comment by molecular** [comment]
> The block time in the Bitcoin Cash is 10 minutes, but it's a statistics, sometimes the block time is longer, even up to 1 hour and sometimes it's shorter. I'd recommend having less than 6 transactions per hour.

There were at least 3 block mined during the time from the first transfer tx broadcast. It wasn't getting mined for whatever reason.

> You should disable shuffling, if it was going while the plugin was working

yes, I had shuffling enabled in both receiving and sending wallet during the process ran. However, no shuffle transactions where created in the sending wallet, since the wallet was fully shuffled.

I'll just write this off as a one-time-occurrence and disable shuffling next time I use the plugin.

Thanks again for an awesomely useful plugin!!! I had wanted this for a long time even before cashuffle existed, just to transfer coins between wallets and not needlessly destroy privacy.
