### ISSUE TITLE
question: do I have to stop shuffling while process runs?

### ISSUE THREAD

**Issue by molecular** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#3]
It says I shouldn't make transactions while it runs, but what about shuffling transactions. It seems the receiving wallet starts shuffling the newly transferred coins right away. Does this interfere or not?

**Comment by KarolTrzeszczkowski** [comment]
The receiving wallet can be safely shuffling with EC, I've just asked people from CashShuffle, I don't know how about other implementations, they don't know either. Thank you for your input.
