### ISSUE TITLE
Show if a transfer was intiated or not

### ISSUE THREAD

**Issue by damascene** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#6]
In interwallet trasfer tab you can see the transfer schedule but there is no way to know which transfers have been initiated and which one havn't .  Please add a column to the time column that shows the status of transfer. (ex. done/waiting)

I've faced some errors trying to use the plugin because of different reasons and I couldn't know if the transfer stopped or not. I had to compare it with history to figure it out.

![resim](https://user-images.githubusercontent.com/411046/61140575-5655db00-a4d4-11e9-8c47-f673fb53ddda.png)

**Comment by KarolTrzeszczkowski** [comment]
Good idea! 
I'd recommend giving more time for transfer.

**Comment by damascene** [comment]
Thank you for the recommendation

**Comment by cculianu** [comment]
I just submitted a pull request #13 which would address this.
