### ISSUE TITLE
Numbers in the Amount column are left alinged

### ISSUE THREAD

**Issue by damascene** [KarolTrzeszczkowski/Inter-Wallet-Transfer-EC-plugin#7]
Numbers in the Amount column are left aligned while it should be aligned to the right
![resim](https://user-images.githubusercontent.com/411046/61141042-56a2a600-a4d5-11e9-8fc1-b5eeda1f50cf.png)

**Comment by KarolTrzeszczkowski** [comment]
Okay, thank you. I will fix it.

**Comment by damascene** [comment]
commit 50438350a20d866fbe8f7bbadf91e4cb664d822d
